---
title: "Module preservation analysis of ROSMAP consensus network"
author: "Thanneer Perumal"
date: "`r date()`"
output: html_document
---
  
```{r libs, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
## It is assumed your working directory is where this file is

# Clear R console screen output
cat("\014")  

# Load require libraries
library(synapseClient)
library(data.table)
library(igraph)
library(org.Hs.eg.db)
library(annotate)
library(tools)
library(biomaRt)
library(rGithubClient)
library(WGCNA)
library(dplyr)
library(RColorBrewer)
library(ggplot2)
library(knitr)
library(stringr)
library(ComplexHeatmap)

synapseLogin()

options(xtable.type="html")

# source utility files from ../R/lib folder
file.sources = list.files('../R/lib',pattern="*.R")
file.sources = sapply(file.sources,function(x){return(paste('../R/lib',x,sep='/'))})
tmp = sapply(file.sources,source,.GlobalEnv)

knitr::opts_chunk$set(
  echo=FALSE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  cache = TRUE)
```

### Download networks
```{r download.data}
# Download adjacency matrices
Data.Files = synQuery('select * from file where projectId=="syn2397881" and fileType == "rda" and method == "rankconsensus" and sparsityMethod == "sparrow2Bonferroni"')
networks = lapply(Data.Files$file.id, function(id){  
  try({
    load(synGet(id)@filePath)
    g = igraph::graph.adjacency(sparseNetwork, mode = 'undirected', weighted = NULL, diag = F)
    return(g)
  }, silent=T)
})
names(networks) = Data.Files$file.disease
```

### Download modules
```{r download.mods}
# Download module assignments
Module.Files = synQuery('select * from file where projectId=="syn2397881" and fileType == "tsv" and method == "rankconsensus" and sparsityMethod == "sparrow2Bonferroni"')
Module.Files = Module.Files[grep('Modules',Module.Files$file.name),]
modules = lapply(Module.Files$file.id, function(id){  
  try({
    tmp = fread(synGet(id)@filePath, data.table=F, header=T)
    
    tmp = split(tmp, factor(tmp$modulelabels))
    len = t(sapply(tmp, dim))
    
    ind = which(len[,1] < 20)
    tmp[ind] = lapply(tmp[ind], function(x){
      x$moduleNumber = 0;
      x$modulelabels = 'NoModule';
      return(x)
    })
    tmp = as.data.frame(rbindlist(tmp))
    
    tmp1 = tmp$modulelabels
    names(tmp1) = tmp$GeneIDs
    return(tmp1)
  }, silent=T)
})
names(modules) = Module.Files$file.disease
modules = modules[names(networks)]
```

### Download enrichment results
```{r download.annotations}
# Download module assignments
Enrich.Files = synQuery('select * from file where projectId=="syn2397881" and fileType == "tsv" and method == "rankconsensus" and sparsityMethod == "sparrow2Bonferroni" and enrichmentMethod == "Fisher" and enrichmentGeneSet == "Enrichr and AD"')
Enrich.Files = Enrich.Files[grep('Enrichment',Enrich.Files$file.name),]
enrichResults = lapply(Enrich.Files$file.id, function(id){  
  try({
    tmp = fread(synGet(id)@filePath, data.table=F, header=T)        
    return(tmp)
  }, silent=T)
})
names(enrichResults) = Enrich.Files$file.disease
enrichResults = enrichResults[names(networks)]
```

### Download expression data
```{r download.expression}
# Download expression data
EXP_ID = 'syn4259377'
EXP = fread(synGet(EXP_ID)@filePath, data.table = F, header=T)

# Download covariates data
COV_ID = 'syn4259379'
COVARIATES = fread(synGet(COV_ID)@filePath, data.table = F, header = T)
COVARIATES = split(COVARIATES, COVARIATES$cogdx)

# Separate expression based on cogdx
exp = lapply(COVARIATES, function(x,EXP) { x = EXP[, colnames(EXP) %in% x$SampleID]; x = cbind(EXP[,'ensembl_gene_id', drop=F],x)}, EXP)
exp = exp[c(4,2,1)]
names(exp) = names(networks)
```

### Get module annotations
```{r module.annotations}
Annotation = list()
for (i in names(networks)){
  modLabels = setdiff(unique(modules[[i]]),"NoModule")  
  
  tmp = unlist(sapply(modLabels, function(x,y){
    y = filter(y, ComparisonName == x & category %in% c("ADRelated", "GO_Biological_Process", "WikiPathways_2015", "Reactome", "OMIM_Disease", "Drug_Perturbations_from_GEO", "TargetScan_microRNA"))
    return(y$GeneSetName[which.min(y$fdr)])
    }, enrichResults[[i]]))  
  Annotation[[i]] = data.frame(moduleName = names(tmp), annotation = tmp)
}

```

### Get overlap statistics
```{r overlap.stats, fig.height = 10, fig.width=20}
comparisons  = combn(names(networks),2)

for (i in 1:dim(comparisons)[2]){
  tmp = overlapStats(modules[[comparisons[1,i]]], modules[[comparisons[2,i]]])
  
  cTable = tmp$countTable %>% data.frame 
  cTable = cTable[!(rownames(cTable) %in% 'NoModule'), !(colnames(cTable) %in% 'NoModule')]
  
  pTable = tmp$pTable
  pTable = -log10(pTable)
  pTable[is.infinite(pTable)] = max(pTable[!is.infinite(pTable)])  
  pTable = pTable[!(rownames(pTable) %in% 'NoModule'), !(colnames(pTable) %in% 'NoModule')]
    
  orTable = tmp$orTable
  orTable[is.infinite(orTable)] = max(orTable[!is.infinite(orTable)])  
  orTable = orTable[!(rownames(orTable) %in% 'NoModule'), !(colnames(orTable) %in% 'NoModule')]
    
  ht1 = Heatmap(cTable, name = 'nOverlap', col = RColorBrewer::brewer.pal(5,'Reds'), row_title = comparisons[1,i], column_title = comparisons[2,i])
  ht2 = Heatmap(pTable, name = '-log10(p.val)', col = RColorBrewer::brewer.pal(5,'Greens'), row_title = comparisons[1,i], column_title = comparisons[2,i])
  ht3 = Heatmap(orTable, name = 'odds ratio', col = RColorBrewer::brewer.pal(5,'Greys'), row_title = comparisons[1,i], column_title = comparisons[2,i])
  draw(ht3 + ht1 + ht2)  
}
```

### Calculate preservation statistics
```{r preservation.stats, fig.height=10, fig.width=20, eval=FALSE}
presAnal = list()
for (ref in names(networks)[-(2)]){
  presAnal[[ref]] = list()
  for (test in names(networks)){
    presAnal[[ref]][[test]] = list()
    if (ref != test){
      plotLists = list()
      presAnal[[ref]][[test]] = modulePreservationAnalysis(networks[[ref]], networks[[test]], modules[[ref]], modules[[test]])    
      }    
    print(paste(ref,test))
    }  
  }
```

```{r plot.data, fig.height=6, fig.width=20}
load('temp.RData')
for (ref in names(networks)[-(2)]){
  for (test in names(networks)){    
    if (ref != test){
      plotLists = list()
      ranks = presAnal[[ref]][[test]]$presRank
      ranks = merge(ranks, Annotation[[ref]], by = 'moduleName')
      
      p.m = ggplot(ranks, aes(x = moduleSize, y = median.rank)) + geom_point(aes(shape = annotation, color = annotation)) 
      p.m = p.m + scale_shape_manual(values = 1:length(unique(ranks$annotation))) #+ theme(legend.position = 'top')
      p.m = p.m + ggtitle(paste('Median Rank,','Reference:',ref,'Test:', test)) #+ geom_text(aes(label= annotation), size=4, hjust=-0.1, vjust = -0.1)
      plotLists[[1]] = p.m
      
      zstat = presAnal[[ref]][[test]]$Z 
      zstat = merge(zstat, Annotation[[ref]], by = 'moduleName')
      
      p.z = ggplot(zstat, aes(x = moduleSize, y = Z.min)) + geom_point(aes(shape = annotation, color= annotation))  + scale_size_manual(values = c(10,10))
      p.z = p.z + scale_y_continuous(limits = c(0, max(zstat$Z.min[is.finite(zstat$Z.min)])+2))
      p.z = p.z + ggtitle(paste('Zstatistics,','Reference:',ref,'Test:', test)) + scale_shape_manual(values = 1:length(unique(zstat$annotation)))
      p.z = p.z + geom_abline(slope = 0, intercept = 2) + geom_abline(slope = 0, intercept = 10)#+ theme(legend.position = 'top')      
      p.z = p.z #+ geom_text(aes(label= annotation), size=4, hjust= -0.1, vjust = -0.1)
      plotLists[[2]] = p.z
      
      multiplot(plotlist = plotLists, cols = 2)
      }
    }
  }
```

